version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: aura_ms
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aura_ms_clients
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10.12.0
    container_name: flyway_migration
    depends_on:
      - postgres
    command: [
      "migrate",
      "-url=jdbc:postgresql://postgres:5432/aura_ms_clients",
      "-user=postgres",
      "-password=postgres"
    ]
    volumes:
      - ./migrations:/flyway/sql

volumes:
  pgdata:
